/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.movie.GUI;

import com.mycompany.movie.Movies.MovieLibrary;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author MU
 */
public class MainMenu extends JPanel {

    public MainMenu(program prog) {
        initComponents();
        MovieLibrary.getMovies();
        
        setName("MainMnue");
        
        Report.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
              
              prog.switchToPanel("Reports");
           }   
           });
        Add.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
//               System.out.println("Add"); 
               
               prog.switchToPanel("AddMovie");
                
           }   
           });
        Delete.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
                
            
              
              prog.switchToPanel("DeleteMovie");

           }   
           });
        recipt.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
                MovieLibrary.getMovies();
               
               prog.switchToPanel("Receipts");
           }   
           });
        screentime.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
                
            
                prog.switchToPanel("AddScreenTime");
            
           }   
           });
        Book.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
                
               
               prog.switchToPanel("MyFrame");
           }   
           });
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Book = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        recipt = new javax.swing.JButton();
        screentime = new javax.swing.JButton();

       

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Movie Ticket Reservation System");

        Book.setText("Book Movie");

        Add.setText("Add Movie");

        Delete.setText("Delete Movie");

        Report.setText("Reports");

        recipt.setText("Receipts");

        screentime.setText("Add ScreenTime");
        screentime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screentimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Add)
                        .addComponent(Delete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Book)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recipt)
                            .addComponent(Report)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(screentime)))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Book)
                    .addComponent(Report))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recipt)
                    .addComponent(Add))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(screentime)
                    .addComponent(Delete))
                .addContainerGap(99, Short.MAX_VALUE))
        );

            }// </editor-fold>//GEN-END:initComponents

    private void screentimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screentimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_screentimeActionPerformed

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Book;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton recipt;
    private javax.swing.JButton screentime;
    // End of variables declaration//GEN-END:variables
}
