
package com.mycompany.movie.GUI;

import com.mycompany.movie.Database;
import com.mycompany.movie.Movies.MovieLibrary;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
*database 
* reports
* panel 
* receipt
 */
public class program extends javax.swing.JFrame {

    /**
     * Creates new form program
     */
    public program() {
        setTitle("Movie Tickets");
        setLocationRelativeTo(null);
        initComponents1();
        MovieLibrary.getMovies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *//*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    */
        private void initComponents1() {
            var lib= new MovieLibrary(Database.listMoviesWithScreenTimes());
       
           
        setSize(700, 450);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        bookSeats1 = new com.mycompany.movie.GUI.BookSeats1(this);
        bookMovie1 = new com.mycompany.movie.GUI.BookMovie1(this);
        receipts = new com.mycompany.movie.GUI.Receipts(this);
        reports = new com.mycompany.movie.GUI.Reports(this);
        addScreenTime = new com.mycompany.movie.GUI.AddScreenTime(this);
        addmovie = new com.mycompany.movie.GUI.AddMovie(this);
        soldSeats=new SoldSeats();
        customerInput=new CustomerInput(this);
        deleteMovie=new DeleteMovie(this);
        
        movieReceipt=new  MovieReceipt1(this);
        mainMenu11=new MainMenu(this);
        // Initialize CardLayout and main panel
         cardLayout = new CardLayout();
         mainPanel = new JPanel(cardLayout);

        // Create the panels
        
        // Add panels to the main panel
        mainPanel.add(mainMenu11, "MainMnue");
        mainPanel.add(bookMovie1, "BookMovie");
        mainPanel.add(bookSeats1, "BookSeats");
        mainPanel.add(movieReceipt, "MovieReceipt");
        mainPanel.add(receipts,"Receipts");
        mainPanel.add(reports,"Reports");
        mainPanel.add(addmovie,"AddMovie");
        mainPanel.add(addScreenTime,"AddScreenTime");
        mainPanel.add(customerInput,"MyFrame");
        mainPanel.add(deleteMovie,"DeleteMovie");
        
        add(mainPanel);
    }

    public void switchToPanel(String panelName) {
        cardLayout.show(mainPanel, panelName);
    }

    public JPanel getPanel(String panelName) {
        for (var comp : mainPanel.getComponents()) {
            if (comp instanceof JPanel && mainPanel.getLayout() instanceof CardLayout) {
                if (panelName.equals(((JPanel) comp).getName())) {
                    return (JPanel) comp;
                }
            }
        }
        return null;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                program prog =new program();
                prog.setLocationRelativeTo(null);
                prog.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private MovieReceipt1 movieReceipt;
    public static BookMovie1 bookMovie1; 
    public static BookSeats1 bookSeats1; 
    public static AddMovie addmovie; 
    public static AddScreenTime addScreenTime;
    public static DeleteMovie deleteMovie;
    public static CustomerInput customerInput;
    public static Receipts receipts;
    public static Reports reports;
    public static SoldSeats soldSeats;
    public static CardLayout cardLayout;
    public static JPanel mainPanel;
    public static MainMenu mainMenu11;
}
