/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.movie.GUI;
import com.mycompany.movie.Book.Customer;

import java.awt.*;
import java.awt.print.Book.*;
import com.mycompany.movie.CLI.Manager;
import com.mycompany.movie.Database;
import com.mycompany.movie.Movies.MovieLibrary;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.event.*;
import com.mycompany.movie.Book.Receipt;
import com.mycompany.movie.CLI.Format;
import java.awt.Font;



/**
 *
 * @author MU
 */
public class Receipts extends JPanel {

    /**
     * Creates new form Receipts
     */
    public Receipts(program prog) {
        initComponents();
        MovieLibrary.getMovies();
        
        setName("Receipts");
        
        Customer cust = new Customer("user",(short)20);
       
        for (Receipt receipt : Database.getAllReceipts()) {
            Recipts.addItem(receipt.getID() + "");
        }
        redo.addActionListener(new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
               output.setText("");

               prog.switchToPanel("MainMnue");
           }});
        
        Show.addActionListener(new ActionListener() {
        @Override
            
            public void actionPerformed(ActionEvent e){
            String getSelectedReceipt = (String) Recipts.getSelectedItem();
            for (Receipt r : Database.getAllReceipts()) {
                if (r.getID() == Integer.parseInt(getSelectedReceipt)) {
                    receipt = r;
                }
            }
            
            
             output.setText(        "\nName : " + receipt.getCustomerName() +
                                    "\nMovie Name : "  + receipt.getMovieName() +
                                    "\nTotal Price : " + receipt.getTotalPrice() + " LE" +
                                    "\nHall ID : "     + receipt.getHallID() +
                                    "\nSeats :  "+ receipt.getSeatIDs()+
                                    "\nDuration : "    + Format.duration(receipt.getStartDate(), receipt.getEndDate()) +
                                    "\nStart Date : "  + Format.date(receipt.getEndDate()) +
                                    "\nEnd Date : "    + Format.date(receipt.getStartDate()));
                    output.setFont(new Font("Arial", Font.PLAIN, 24));
                    output.setBorder(new EmptyBorder(20, 20, 20, 20));
            
            }
        });        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redo = new JButton();
        Recipts = new JComboBox<>();
        jLabel1 = new JLabel();
        Show = new JButton();
        jScrollPane1 = new JScrollPane();
        output = new JTextArea();

   

        redo.setBackground(new Color(51, 153, 255));
        redo.setForeground(new Color(255, 255, 255));
        redo.setText("Back");
        redo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });

        jLabel1.setText("Receipts");

        Show.setText("Show Receipt");

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Recipts, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Show)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(redo)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(Recipts, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(redo)
                    .addComponent(Show))
                .addGap(19, 19, 19))
        );

       
    }// </editor-fold>//GEN-END:initComponents

    private void redoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Receipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Receipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Receipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Receipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Receipts().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JComboBox<String> Recipts;
    private JButton Show;
    private JLabel jLabel1;
    private JScrollPane jScrollPane1;
    private JTextArea output;
    private JButton redo;
    
    private Receipt receipt;
    // End of variables declaration//GEN-END:variables
}
