
//package com.mycompany.movie.GUI;
//
//import com.mycompany.movie.GUI.MainMenu11;
//import com.mycompany.movie.GUI.SoldSeats;
//import java.awt.FlowLayout;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import javax.swing.JFrame;
//import javax.swing.JPanel;
//
//public class ReportsPanel extends JPanel {
//
//    /**
//     * Creates new form Reports
//     */
//    public ReportsPanel() {
//        initComponents();
//        
//         redo.addActionListener(new ActionListener(){
//           @Override
//           public void actionPerformed(ActionEvent e){
//               MainMenu11 main = new MainMenu11();
//               main.setVisible(true);
//               setVisible(false);
//           }   
//           });
//         soldseat.addActionListener(new ActionListener(){
//           @Override
//           public void actionPerformed(ActionEvent e){
//               SoldSeats ss = new SoldSeats();
//               ss.setVisible(true);
//               setVisible(false);
//               
//           }   
//           });
//        
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        redo = new javax.swing.JButton();
//        soldseat = new javax.swing.JButton();
//        mostwatch = new javax.swing.JButton();
//        crowdtime = new javax.swing.JButton();
//        numberseat = new javax.swing.JButton();
//
//       
//
//        redo.setBackground(new java.awt.Color(51, 153, 255));
//        redo.setForeground(new java.awt.Color(255, 255, 255));
//        redo.setText("Back");
//        redo.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                redoActionPerformed(evt);
//            }
//        });
//
//        soldseat.setText("Number of Sold Seats");
//        soldseat.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                soldseatActionPerformed(evt);
//            }
//        });
//
//        mostwatch.setText("Most Watched Movie");
//
//        crowdtime.setText("Get Crowded Time");
//
//        numberseat.setText("Get Number of Seats");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(redo)
//                .addGap(15, 15, 15))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(175, 175, 175)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(soldseat)
//                    .addComponent(mostwatch)
//                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                        .addComponent(crowdtime)
//                        .addComponent(numberseat)))
//                .addContainerGap(157, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(15, 15, 15)
//                .addComponent(redo)
//                .addGap(28, 28, 28)
//                .addComponent(soldseat)
//                .addGap(28, 28, 28)
//                .addComponent(mostwatch)
//                .addGap(30, 30, 30)
//                .addComponent(crowdtime)
//                .addGap(27, 27, 27)
//                .addComponent(numberseat)
//                .addContainerGap(98, Short.MAX_VALUE))
//        );
//
//        
//    }// </editor-fold>                        
//
//    private void redoActionPerformed(java.awt.event.ActionEvent evt) {                                     
//        // TODO add your handling code here:
//    }                                    
//
//    private void soldseatActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//    }                                        
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Reports().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify                     
//    private javax.swing.JButton crowdtime;
//    private javax.swing.JButton mostwatch;
//    private javax.swing.JButton numberseat;
//    private javax.swing.JButton redo;
//    private javax.swing.JButton soldseat;
//    // End of variables declaration                   
//}